<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="1" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-05-11T01:44:26 GMT+05:30" name="Suite 1" finished-at="2021-05-11T01:45:23 GMT+05:30" duration-ms="57601">
    <groups>
    </groups>
    <test started-at="2021-05-11T01:44:26 GMT+05:30" name="WalletHub_Assignments" finished-at="2021-05-11T01:45:23 GMT+05:30" duration-ms="57601">
      <class name="Facebook_test.Facebooktest">
        <test-method is-config="true" signature="setup()[pri:0, instance:Facebook_test.Facebooktest@72cde7cc]" started-at="2021-05-11T01:44:26 GMT+05:30" name="setup" finished-at="2021-05-11T01:44:35 GMT+05:30" duration-ms="9047" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="go_to_facebook_login()[pri:1, instance:Facebook_test.Facebooktest@72cde7cc]" started-at="2021-05-11T01:45:12 GMT+05:30" name="go_to_facebook_login" finished-at="2021-05-11T01:45:13 GMT+05:30" duration-ms="14" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [test insurance company metatitle test] but found [Facebook - Log In or Sign Up]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [test insurance company metatitle test] but found [Facebook - Log In or Sign Up]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Facebook_pages.Landing_page.verifyTitle(Landing_page.java:25)
at Facebook_test.Facebooktest.go_to_facebook_login(Facebooktest.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- go_to_facebook_login -->
        <test-method signature="navigate_to_homepage_set_status()[pri:2, instance:Facebook_test.Facebooktest@72cde7cc]" started-at="2021-05-11T01:45:13 GMT+05:30" name="navigate_to_homepage_set_status" finished-at="2021-05-11T01:45:23 GMT+05:30" duration-ms="10049" status="FAIL">
          <exception class="java.lang.Exception">
            <message>
              <![CDATA[Not able to get to the home page]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Exception: Not able to get to the home page
at Facebook_pages.Home_page.verify_Account_Name(Home_page.java:28)
at Facebook_test.Facebooktest.navigate_to_homepage_set_status(Facebooktest.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigate_to_homepage_set_status -->
        <test-method is-config="true" signature="clear()[pri:0, instance:Facebook_test.Facebooktest@72cde7cc]" started-at="2021-05-11T01:45:23 GMT+05:30" name="clear" finished-at="2021-05-11T01:45:23 GMT+05:30" duration-ms="907" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clear -->
      </class> <!-- Facebook_test.Facebooktest -->
      <class name="Wallethub_test.wallethub_assignment">
        <test-method is-config="true" signature="setup()[pri:0, instance:Wallethub_test.wallethub_assignment@67080771]" started-at="2021-05-11T01:44:35 GMT+05:30" name="setup" finished-at="2021-05-11T01:44:47 GMT+05:30" duration-ms="11834" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="go_to_wallethub_login()[pri:1, instance:Wallethub_test.wallethub_assignment@67080771]" started-at="2021-05-11T01:44:47 GMT+05:30" name="go_to_wallethub_login" finished-at="2021-05-11T01:45:05 GMT+05:30" duration-ms="17931" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- go_to_wallethub_login -->
        <test-method signature="check_stars()[pri:2, instance:Wallethub_test.wallethub_assignment@67080771]" started-at="2021-05-11T01:45:05 GMT+05:30" name="check_stars" finished-at="2021-05-11T01:45:12 GMT+05:30" duration-ms="7740" status="FAIL">
          <exception class="java.lang.Exception">
            <message>
              <![CDATA[Can't post the review, system faced error,please check it]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Exception: Can't post the review, system faced error,please check it
at Wallethub_pages.Wallet_check_stars.write_review(Wallet_check_stars.java:90)
at Wallethub_test.wallethub_assignment.check_stars(wallethub_assignment.java:63)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- check_stars -->
      </class> <!-- Wallethub_test.wallethub_assignment -->
    </test> <!-- WalletHub_Assignments -->
  </suite> <!-- Suite 1 -->
</testng-results>
